language: node_js
node_js: "4.1"
env:
    - CXX=g++-4.9
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install -qq g++-4.9 libgif-dev
    - npm install -g typescript typings nodeunit
branches:
    only:
        - typescript
script: make && make test
notifications:
    on_failure: always
    on_success: never
