language: node_js
node_js: "4.1"
env:
    - CXX=g++-4.8
before_install:
    - npm install -g typescript typings nodeunit
branches:
    only:
        - typescript
script: make && make test
notifications:
    on_failure: always
    on_success: never
